config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get 'pages/show'
  get 'pages/getNews'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
require 'rubygems'
require 'readability'
require 'open-uri'

class PagesController < ApplicationController
  
  def index    
  end

  def getNews
    url = params[:url]    
    @source = open(url).read
    @content = Readability::Document.new(@source).content    
    respond_to do |format|      
      format.json { render json: @source }
    end
  end

  def show
    url = params[:page]
    @source = open(url).read
    @content = Readability::Document.new(@source).content
    @rbody = Readability::Document.new(@source, 
      :tags => %w[div p img a], 
      :attributes => %w[src href], 
      :remove_empty_nodes => false)    
    p @rbody
    p @rbody.images    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a id="home_link" class="navbar-brand" onClick="displayDataAtFirstTime();" href="<%= root_path %>">
        <img alt="Brand" width="25px" src="<%= asset_path('icon_letter_N_blue.png') %>">
      </a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsReader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<span style="display:none" id="url_page_get_news">
  <%= url_for(only_path: false) + pages_getNews_path %>
</span>
<span style="display:none" id="url_page_detail">
  <%= pages_show_path %>
</span>

<div id="data" style="display:none;">
  <%= raw(@source) %>
</div>

<div class="wrapper_content">
  <div id="content"></div>
  <div class='more_button' style="display:none;">
    <span onclick="loadMore(this);" page="0">More</span>
  <div>
</div>

app/views/pages/show.html.erb
<div class="content_detail_wrapper">
  <%= raw(@content) %>
</div>